### ISSUE TITLE
Add Option to Disable Inline CSS

### ISSUE THREAD

**Issue by bgardner** [copyblogger/genesis-simple-faq#28]
As the title explains, let's add a filter to completely remove the inline CSS from the head, in lieu of the theme adding those critical styles to the theme style sheet.

**Comment by nickcernis** [comment]
Confirmed that `add_filter( 'gs_faq_print_styles', '__return_false' );` suppresses inline CSS output:

<img width="999" alt="test_faq_page_and_test_faq_page" src="https://user-images.githubusercontent.com/647669/30175863-32d2dda2-93f8-11e7-833d-9e3353fa5a19.png">
