### ISSUE TITLE
Add category ID column to FAQ categories page

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-faq#30]
As suggested [here](https://wordpress.org/support/topic/include-category-id-in-dashboard/), we could add each category's ID to a column at Simple FAQs → Categories (or show the shortcode to use to display that category): 

`/wp-admin/edit-tags.php?taxonomy=gs_faq_categories&post_type=gs_faq`

**Comment by cjkoepke** [comment]
@nickcernis Added shortcode example to the category page:

<img width="821" alt="screenshot 2017-09-06 14 11 53" src="https://user-images.githubusercontent.com/2815568/30132387-675a30d4-930d-11e7-87f7-7cc3ce43ec15.png">

**Comment by nickcernis** [comment]
Confirmed!

<img width="891" alt="categories_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30175097-45524376-93f5-11e7-9b3f-2658ef5e94be.png">
