### ISSUE TITLE
Answers are hidden if JavaScript is disabled.

### ISSUE THREAD

**Issue by timothyjensen** [copyblogger/genesis-simple-faq#31]
If a user has JS disabled or if there is a JS error on the site, then answers would not be made visible on click.  Granted, this would be a rare occasion, but it might be worth showing answers by default and hiding them via JS vs the other way around.  

The tradeoff with this suggestion is that there would be a brief flash on the page where answers are visible before they become hidden.

**Comment by cjkoepke** [comment]
Actually would be really easy to default FAQ's to an open state if JS is turned of. Great idea!

**Comment by cjkoepke** [comment]
@nickcernis I've added support for non-JS. Simply hides the toggle button and shows the headers along with their descriptions by default.

**Comment by nickcernis** [comment]
Looks good.

### JS enabled

<img width="387" alt="test_faq_page" src="https://user-images.githubusercontent.com/647669/30175199-9affdc70-93f5-11e7-835f-67aa8a558485.png">

### JS disabled

<img width="283" alt="test_faq_page" src="https://user-images.githubusercontent.com/647669/30175228-b36b3c46-93f5-11e7-9dea-865518a6f22c.png">
